// src/app/users/components/user/user.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {UserInterface} from '../../../shared/types/user.interface';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.scss']
})
export class UserComponent implements OnInit {
  @Input('user') userProps: UserInterface;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="user-item">
  <div class="avatar">
    <img [src]="userProps.avatar_url" [alt]="userProps.login" />
  </div>
  <div class="login-user">
    <a [routerLink]="['/user', userProps.login]">{{userProps.login}}</a>
<!--    <Link to={`/user/${user.login}`}>{user.login}</Link>-->
  </div>
  <div class="repos">Repos: ##</div>
</div>

// src/components/User/User.tsx
import React, {FC} from 'react';
import {Link} from 'react-router-dom';
import {UserInterface} from '../../common/types';
import './User.scss';

interface UserPropsInterface {
  user: UserInterface
}

export const User: FC<UserPropsInterface> = ({user}) => {
  return (
    <div className="user-item" key={user.id}>
      <div className="avatar">
        <img src={user.avatar_url} alt={user.login} />
      </div>
      <div className="login-user">
        <Link to={`/user/${user.login}`}>{user.login}</Link>
      </div>
      <div className="repos">Repos: ##</div>
    </div>
  )
}
